# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  omniauth_provider_key: <%= ENV["113618755330635"] %>
  omniauth_provider_secret: <%= ENV["4d6699ebad162fe4e5b90ffbbbe68876"] %>
  email_provider_username: <%= ENV["cash.friends.tool"] %>
  email_provider_password: <%= ENV["SteffiIstCool"] %>
  domain_name: <%= ENV["wgtool"] %>
  secret_key_base: 975aaa8c1dcb42b66dcfa17884a20e3e626f1ea7332a58a06ee6742b2cd121ca37f81a59a6479ec225f649b70c86f470e6344494a5f14874d7e23062919165a5

test:
  secret_key_base: cf6333c1ac85b7714ba26c99c91d6b459bd2b668c8432f51873a464e5a57f5d6c715738b989814ebdec9e12701d9240ee3f3276eed6d6c797fce38486eeefc7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ENV["cash.friends.tool"] %>
  email_provider_password: <%= ENV["SteffiIstCool"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %> 
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
