require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AccountingsController do

  # This should return the minimal set of attributes required to create a valid
  # Accounting. As you add validations to Accounting, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "group_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AccountingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all accountings as @accountings" do
      accounting = Accounting.create! valid_attributes
      get :index, {}, valid_session
      assigns(:accountings).should eq([accounting])
    end
  end

  describe "GET show" do
    it "assigns the requested accounting as @accounting" do
      accounting = Accounting.create! valid_attributes
      get :show, {:id => accounting.to_param}, valid_session
      assigns(:accounting).should eq(accounting)
    end
  end

  describe "GET new" do
    it "assigns a new accounting as @accounting" do
      get :new, {}, valid_session
      assigns(:accounting).should be_a_new(Accounting)
    end
  end

  describe "GET edit" do
    it "assigns the requested accounting as @accounting" do
      accounting = Accounting.create! valid_attributes
      get :edit, {:id => accounting.to_param}, valid_session
      assigns(:accounting).should eq(accounting)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Accounting" do
        expect {
          post :create, {:accounting => valid_attributes}, valid_session
        }.to change(Accounting, :count).by(1)
      end

      it "assigns a newly created accounting as @accounting" do
        post :create, {:accounting => valid_attributes}, valid_session
        assigns(:accounting).should be_a(Accounting)
        assigns(:accounting).should be_persisted
      end

      it "redirects to the created accounting" do
        post :create, {:accounting => valid_attributes}, valid_session
        response.should redirect_to(Accounting.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved accounting as @accounting" do
        # Trigger the behavior that occurs when invalid params are submitted
        Accounting.any_instance.stub(:save).and_return(false)
        post :create, {:accounting => { "group_id" => "invalid value" }}, valid_session
        assigns(:accounting).should be_a_new(Accounting)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Accounting.any_instance.stub(:save).and_return(false)
        post :create, {:accounting => { "group_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested accounting" do
        accounting = Accounting.create! valid_attributes
        # Assuming there are no other accountings in the database, this
        # specifies that the Accounting created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Accounting.any_instance.should_receive(:update).with({ "group_id" => "1" })
        put :update, {:id => accounting.to_param, :accounting => { "group_id" => "1" }}, valid_session
      end

      it "assigns the requested accounting as @accounting" do
        accounting = Accounting.create! valid_attributes
        put :update, {:id => accounting.to_param, :accounting => valid_attributes}, valid_session
        assigns(:accounting).should eq(accounting)
      end

      it "redirects to the accounting" do
        accounting = Accounting.create! valid_attributes
        put :update, {:id => accounting.to_param, :accounting => valid_attributes}, valid_session
        response.should redirect_to(accounting)
      end
    end

    describe "with invalid params" do
      it "assigns the accounting as @accounting" do
        accounting = Accounting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Accounting.any_instance.stub(:save).and_return(false)
        put :update, {:id => accounting.to_param, :accounting => { "group_id" => "invalid value" }}, valid_session
        assigns(:accounting).should eq(accounting)
      end

      it "re-renders the 'edit' template" do
        accounting = Accounting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Accounting.any_instance.stub(:save).and_return(false)
        put :update, {:id => accounting.to_param, :accounting => { "group_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested accounting" do
      accounting = Accounting.create! valid_attributes
      expect {
        delete :destroy, {:id => accounting.to_param}, valid_session
      }.to change(Accounting, :count).by(-1)
    end

    it "redirects to the accountings list" do
      accounting = Accounting.create! valid_attributes
      delete :destroy, {:id => accounting.to_param}, valid_session
      response.should redirect_to(accountings_url)
    end
  end

end
